# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

    # Run the welcome/run job in its own container
    jobs:
    test:
      docker:
        - image: circleci/android:api-28-alpha  # gcloud is baked into this image
      steps:
        - run:
            name: Build debug APK and release APK
            command: |
              ./gradlew :app:assembleDebug
              ./gradlew :app:assembleDebugAndroidTest
        - run:
            name: Store Google Service Account
            command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
        - run:
            name: Authorize gcloud and set config defaults
            command: |
              sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
              sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        - run:
            name: Test with Firebase Test Lab
            command: >
              sudo gcloud firebase test android run \
                --app <local_server_path>/<app_apk>.apk \
                --test <local_server_path>/<app_test_apk>.apk \
                --results-bucket cloud-test-${GOOGLE_PROJECT_ID}
